export {
  crmCustomerProfileValues,
  crmCustomers,
  crmCustomerTags,
  crmCustomerTypes,
  crmFollowUpRecords,
  crmProfileFields,
  type CrmCustomerProfileValueRow,
  type CrmCustomerRow,
  type CrmCustomerTagRow,
  type CrmCustomerTypeRow,
  type CrmFollowUpRecordRow,
  type CrmProfileFieldRow,
  type NewCrmCustomerProfileValueRow,
  type NewCrmCustomerRow,
  type NewCrmCustomerTagRow,
  type NewCrmCustomerTypeRow,
  type NewCrmFollowUpRecordRow,
  type NewCrmProfileFieldRow,
} from './crm'
