export {
  crmCustomerProfileValues,
  crmCustomers,
  crmCustomerTypes,
  crmFollowUpRecords,
  crmFollowUpStatuses,
  crmProfileFields,
  type CrmCustomerProfileValueRow,
  type CrmCustomerRow,
  type CrmCustomerTypeRow,
  type CrmFollowUpRecordRow,
  type CrmFollowUpStatusRow,
  type CrmProfileFieldRow,
  type NewCrmCustomerProfileValueRow,
  type NewCrmCustomerRow,
  type NewCrmCustomerTypeRow,
  type NewCrmFollowUpRecordRow,
  type NewCrmFollowUpStatusRow,
  type NewCrmProfileFieldRow,
} from './crm'
