import { agents } from '@reeka-office/domain-agent/schema'
import { sql } from 'drizzle-orm'
import {
  datetime,
  foreignKey,
  index,
  int,
  mysqlTable,
  uniqueIndex,
  varchar,
} from 'drizzle-orm/mysql-core'

export const apm = mysqlTable('agent_performance_monthly', {
  id: int('id').autoincrement().primaryKey(),
  agentCode: varchar('agent_code', { length: 8 }).notNull(),
  year: int('year').notNull(),
  month: int('month').notNull(),
  nsc: int('nsc').notNull().default(0),
  nscSum: int('nsc_sum').notNull().default(0),
  netAfycSum: int('net_afyc_sum').notNull().default(0),
  netAfyp: int('net_afyp').notNull().default(0),
  netAfypSum: int('net_afyp_sum').notNull().default(0),
  netAfypAssigned: int('net_afyp_assigned').notNull().default(0),
  netAfypAssignedSum: int('net_afyp_assigned_sum').notNull().default(0),
  nscHp: int('nsc_hp').notNull().default(0),
  nscHpSum: int('nsc_hp_sum').notNull().default(0),
  netAfypHp: int('net_afyp_hp').notNull().default(0),
  netAfypHpSum: int('net_afyp_hp_sum').notNull().default(0),
  netAfypH: int('net_afyp_h').notNull().default(0),
  netAfypHSum: int('net_afyp_h_sum').notNull().default(0),
  netCaseH: int('net_case_h').notNull().default(0),
  netCaseHSum: int('net_case_h_sum').notNull().default(0),
  netCase: int('net_case').notNull().default(0),
  netCaseSum: int('net_case_sum').notNull().default(0),
  netCaseAssigned: int('net_case_assigned').notNull().default(0),
  netCaseAssignedSum: int('net_case_assigned_sum').notNull().default(0),
  amm: int('amm').notNull().default(0),
  ammSum: int('amm_sum').notNull().default(0),
  ammAssigned: int('amm_assigned').notNull().default(0),
  ammAssignedSum: int('amm_assigned_sum').notNull().default(0),
  fycSum: int('fyc_sum').notNull().default(0),
  fycAssignedSum: int('fyc_assigned_sum').notNull().default(0),
  rycSum: int('ryc_sum').notNull().default(0),
  rycAssignedSum: int('ryc_assigned_sum').notNull().default(0),
  renewalRate: int('renewal_rate').notNull().default(0),
  renewalRateTeam: int('renewal_rate_team').notNull().default(0),
  isMdrt: int('is_mdrt').notNull().default(0).$type<boolean>(),
  isQualified: int('is_qualified').notNull().default(0),
  isQualifiedAssigned: int('is_qualified_assigned').notNull().default(0),
  isQualifiedNextMonth: int('is_qualified_next_month'),
  qualifiedGap: int('qualified_gap'),
  qualifiedGapNextMonth: int('qualified_gap_next_month'),
  createdAt: datetime('created_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
  updatedAt: datetime('updated_at').default(sql`CURRENT_TIMESTAMP`).$onUpdateFn(() => sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
  foreignKey({
    name: 'apm_agent_code_fk',
    columns: [table.agentCode],
    foreignColumns: [agents.agentCode],
  }).onDelete('no action'),
  uniqueIndex('apm_period_udx').on(
    table.agentCode,
    table.year,
    table.month,
  ),
  index('apm_period_idx').on(table.year, table.month),
  index('apm_agent_year_idx').on(table.agentCode, table.year),
])

export type ApmRow = typeof apm.$inferSelect
export type NewApmRow = typeof apm.$inferInsert
